import type { ComponentGroup } from "./types.js";

// Each page lives in ./components/<slug>.ts. These lists are the only other
// place a component is named: they set its group and its position in the nav.
export const groupOrder = {
  actions: [
    "button",
    "toggle-button",
    "link",
    "file-trigger",
    "visually-hidden",
    "keybinding-hint",
    "meter",
    "progress-bar",
    "alert",
    "status",
    "error-summary",
    "separator",
    "toast",
    "toolbar",
    "split-button",
    "drop-zone",
    "avatar",
    "suggestions",
    "feedback",
    "copy-button",
  ],
  charts: [
    "bar-chart",
    "column-chart",
    "line-chart",
    "area-chart",
    "pie-chart",
    "candlestick-chart",
    "scatter-chart",
    "dumbbell-chart",
    "boxplot-chart",
    "open-to-close-chart",
    "lollipop-chart",
    "stacked-bar-chart",
    "stacked-column-chart",
    "histogram-chart",
    "heatmap-chart",
    "sankey-chart",
    "map-chart",
  ],
  fields: [
    "text-area",
    "composer",
    "character-count",
    "mention-field",
    "code-editor",
    "fieldset",
    "text-field",
    "password-field",
    "search-field",
    "checkbox",
    "radio",
    "switch",
    "number-field",
    "slider",
    "output",
    "pin-input",
    "range-slider",
    "color-field",
    "date-field",
    "tag-picker",
    "color-swatch-picker",
    "editable",
    "rating",
  ],
  navigation: [
    "accordion",
    "disclosure",
    "reasoning",
    "tabs",
    "breadcrumbs",
    "list-box",
    "menu",
    "tag-group",
    "resizer",
    "connect",
    "floating-panel",
    "inventory",
    "grid-list",
    "table",
    "comparison",
    "tree-grid",
    "skip-link",
    "context-menu",
    "menubar",
    "tree",
    "carousel",
    "feed",
    "messages",
    "citation",
    "message",
    "busy-region",
    "pagination",
    "timeline",
    "navigation-menu",
    "steps",
  ],
  pickers: [
    "select",
    "combobox",
    "autocomplete",
    "modal",
    "dialog",
    "alert-dialog",
    "popover",
    "tour",
    "tooltip",
    "calendar",
    "color-picker",
    "date-picker",
    "time-picker",
    "range-calendar",
    "date-range-picker",
    "preview",
    "drawer",
  ],
} satisfies Record<ComponentGroup["id"], string[]>;

export const groupMeta = [
  {
    id: "actions",
    title: "Actions",
    description: "Presses, links, uploads, and hidden helper text.",
  },
  {
    id: "charts",
    title: "Charts",
    description: "Accessible visual and tabular views of quantitative values.",
  },
  { id: "fields", title: "Fields", description: "Inputs and choices that collect values." },
  {
    id: "navigation",
    title: "Navigation",
    description: "Disclosure, navigation, and collection patterns.",
  },
  { id: "pickers", title: "Pickers and overlays", description: "Choices and floating layers." },
] satisfies Omit<ComponentGroup, "components">[];
