import { describe, expect, it } from "vitest";
import * as api from "./index.js";

const publicComponents = [
  "Accordion",
  "AccordionHeader",
  "AccordionItem",
  "AccordionPanel",
  "AccordionTrigger",
  "AlertDialog",
  "AlertDialogContent",
  "BreadcrumbLink",
  "Breadcrumbs",
  "Button",
  "Checkbox",
  "CheckboxGroup",
  "Combobox",
  "ComboboxContent",
  "ComboboxInput",
  "ComboboxOption",
  "Description",
  "Dialog",
  "DialogContent",
  "DialogTrigger",
  "Disclosure",
  "DisclosurePanel",
  "DisclosureTrigger",
  "FieldError",
  "Fieldset",
  "FileTrigger",
  "Input",
  "Label",
  "Legend",
  "Link",
  "ListBox",
  "ListBoxItem",
  "ListBoxSection",
  "Menu",
  "MenuContent",
  "MenuItem",
  "MenuSection",
  "MenuTrigger",
  "NumberField",
  "Popover",
  "PopoverArrow",
  "PopoverContent",
  "PopoverTrigger",
  "Radio",
  "RadioGroup",
  "SearchField",
  "SearchFieldClear",
  "SearchFieldInput",
  "Select",
  "SelectContent",
  "SelectOption",
  "SelectTrigger",
  "SelectValue",
  "Slider",
  "Switch",
  "Tab",
  "TabList",
  "TabPanel",
  "Tabs",
  "TextArea",
  "TextField",
  "ToggleButton",
  "ToggleButtonGroup",
  "Tooltip",
  "TooltipContent",
  "TooltipTrigger",
  "VisuallyHidden",
].sort();

describe("public React API", () => {
  it("exports only the graduated alpha component catalog", () => {
    expect(Object.keys(api).sort()).toEqual(publicComponents);
  });
});
